#端口
server:
  port: 8878
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_schema
    username: root
    password: Zhang123456.
  # jpa配置
  jpa:
    database: MySQL
    show-sql: false